# Generated by Django 2.1.5 on 2019-02-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('confirmKey', models.CharField(blank=True, max_length=20, null=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
